version: 3

tasks:
  tpl:
    desc: Generate config/env files with secrets and values
    cmd: docker compose run --rm utils maketemplate

  sops:
    desc: Edit secrets
    cmd: sops edit secrets.yml
