global:
  timezone: "Asia/Bangkok"
  domain: example.com
  name: Sweet Home
  notification:
    telegram:
      botToken: ""
      channelId: ""

watchtower:
  notification:
    telegram:
      channelId: ""

wgeasy:
  subdomain: wgeasy
  admin:
    username: ""
    password: ""

homeassistant:
  oidc:
    clientId: ""
    clientSecret: ""

acmesh:
  cloudflare:
    accountId: ""
    zoneId: ""
    token: ""

cloudflareDdns:
  apiToken: ""
  zone: ""
  subdomain: ddns

cloudflareTunnel:
  accountId: ""
  tunnelId: ""
  tunnelSecret: ""

crowdsecfirewall:
  capiKey: ""

crowdsec:
  enrollKey: ""
  instanceName: orangepi

pocketId:
  subdomain: pocketid
  encryptionKey: ""

rauthy:
  subdomain: rauthy
  adminEmail: ""
  secretRaft: ""
  secretApi: ""
  smtpHost: ""
  smtpUser: ""
  smtpPass: ""
  smtpFrom: ""
  encryptionKeys:
    - id: ""
      key: ""

oauth2proxy:
  subdomain: oauth2proxy
  clientId: ""
  clientSecret: ""
  cookieSecret: ""

duplicity:
  s3:
    region: apac
    endpoint: "https://<account-id>.r2.cloudflarestorage.com"
    bucket: home-assistant
    prefix: backup
    accessKey: ""
    secretKey: ""
  notification:
    telegram:
      channelId: ""
