global:
  timezone: "Asia/Bangkok"
  domain: example.com
  sslipioDomain: local.example.com
  machineIp: 192.168.1.100
  name: Sweet Home
  notification:
    telegram:
      botToken: ""
      channelId: ""
  trustedCidrs:
    local:
      - 192.168.0.0/16
      - 10.0.0.0/8
      - 172.17.0.0/16
      - 172.18.0.0/16
    cloudflare:
      # Cloudflare IPs https://www.cloudflare.com/ips-v4/
      - 173.245.48.0/20
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 141.101.64.0/18
      - 108.162.192.0/18
      - 190.93.240.0/20
      - 188.114.96.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 162.158.0.0/15
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 172.64.0.0/13
      - 131.0.72.0/22

watchtower:
  notification:
    telegram:
      channelId: ""

wgeasy:
  subdomain: wgeasy
  admin:
    username: ""
    password: ""

homeassistant:
  subdomain: homeassistant
  oidc:
    clientId: ""
    clientSecret: ""

acmesh:
  cloudflare:
    accountId: ""
    zoneId: ""
    token: ""

cloudflareDdns:
  apiToken: ""
  zone: ""
  subdomain: ddns

cloudflareTunnel:
  accountId: ""
  tunnelId: ""
  tunnelSecret: ""

crowdsecfirewall:
  capiKey: ""

crowdsec:
  enrollKey: ""
  instanceName: orangepi

pocketId:
  subdomain: pocketid
  encryptionKey: ""

rauthy:
  subdomain: rauthy
  adminEmail: ""
  secretRaft: ""
  secretApi: ""
  smtpHost: ""
  smtpUser: ""
  smtpPass: ""
  smtpFrom: ""
  encryptionKeys:
    - id: ""
      key: ""

oauth2proxy:
  subdomain: oauth2proxy
  clientId: ""
  clientSecret: ""
  cookieSecret: ""

duplicity:
  s3:
    region: apac
    endpoint: "https://<account-id>.r2.cloudflarestorage.com"
    bucket: home-assistant
    prefix: backup
    accessKey: ""
    secretKey: ""
  notification:
    telegram:
      channelId: ""

portainer:
  subdomain: portainer
  license: ""

memos:
  subdomain: memos

actual:
  subdomain: actual

glances:
  subdomain: glances

adguardhome:
  subdomain: adguardhome

traefik:
  subdomain: traefik
  crowdsec:
    capiKey: ""

termix:
  subdomain: termix
