services:
  rauthy:
    image: ghcr.io/moonlight8978/rauthy:latest
    user: "${NON_ROOT_USER}"
    volumes:
      - "${DATA_ROOT}/addons/rauthy/data:/app/data"
      - ./config.toml:/app/config.toml
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.rauthy.loadbalancer.server.port=8080
      - traefik.docker.network=edge
    networks:
      - edge
