services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    user: "${NON_ROOT_USER}"
    env_file:
      - .env
    volumes:
      - /run/dbus:/run/dbus:ro
      - "${DATA_ROOT}/data:/config"
      - ./secrets.yaml:/config/secrets.yaml:ro
      - ./homeassistant/entrypoint.sh:/entrypoint.sh:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "--output",
          "/dev/null",
          "http://localhost:8123",
        ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      adguardhome:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      - traefik.docker.network=edge
    networks:
      - edge
