services:
  traefik:
    image: traefik:v3
    ports:
      # Internal Web
      - "${LAN_HOST}:80:10080"
      - "${LAN_HOST}:443:10443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - /var/log/traefik:/var/log/traefik
      - "${DATA_ROOT}/addons/acmesh/data:/acme.sh:ro"
      - "${DATA_ROOT}/addons/traefik/plugins-storage:/plugins-storage"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - dockerproxy
    security_opt:
      - no-new-privileges:true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dockerproxy
      - ingress
      - edge
