services:
  utils:
    image: ghcr.io/moonlight8978/homeassistant-container-toolkit:latest
    working_dir: /templates
    profiles:
      - task
    user: "${NON_ROOT_USER}"
    volumes:
      - ${WORKDIR}:/templates
      - ./bin:/usr/local/bin:ro
      - ${XDG_CONFIG_ROOT}/sops/age:/.config/sops/age:ro
      - ${TOOLS_ROOT}:/tools:ro
