services: 
  portainer:
    image: portainer/portainer-ee:alpine
    entrypoint: /entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${DATA_ROOT}/addons/portainer/data:/data"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
