services:
  acmesh:
    image: neilpang/acme.sh:latest
    command: daemon
    user: "${NON_ROOT_USER}"
    env_file: .env
    volumes:
      - "${DATA_ROOT}/addons/acmesh/data:/acme.sh"
    restart: unless-stopped

  acmesh-issue:
    image: neilpang/acme.sh:latest
    entrypoint: /entrypoint.sh
    user: "${NON_ROOT_USER}"
    profiles:
      - task
    env_file: .env
    volumes:
      - "${DATA_ROOT}/addons/acmesh/data:/acme.sh"
      - ./issue-entrypoint.sh:/entrypoint.sh
