services:
  acmesh:
    image: neilpang/acme.sh:latest
    command: daemon
    env_file: .env
    volumes:
      - "${DATA_ROOT}/addons/acmesh/data:/acme.sh"
    restart: unless-stopped
    stdin_open: true
    tty: true
